-- dummy data generator

if object_id ('tempdb..#people','u') is not null
    drop table #people
if object_id ('tempdb..#people','u') is null
    create table #people (ID int identity, F_NM varchar(50), L_NM varchar(50), primary key nonclustered(F_NM, L_NM))

if object_id ('tempdb..#place','u') is not null
    drop table #place
if object_id ('tempdb..#place','u') is null
    create table #place (ID int identity, C_NM varchar(1000), S_NM char(2), unique nonclustered (S_NM, C_NM))

if object_id ('tempdb..#zip_3','u') is not null
    drop table #zip_3
if object_id ('tempdb..#zip_3','u') is null    
    create table #zip_3 (ID int identity, ZIP3 char(3) primary key nonclustered, S_NM char(2))

if object_id ('tempdb..#adrs','u') is not null
    drop table #adrs
if object_id ('tempdb..#adrs','u') is null    
    create table #adrs (ID int identity, add1 varchar(100), add2 varchar(100), unique nonclustered (add1, add2))    

DECLARE @StartDate AS date = dateadd(year,-65,dateadd(day,1,eomonth(getdate(),-1)))
DECLARE @EndDate AS date = eomonth(getdate(),-1);

if object_id ('tempdb..#dummy_MBR','u') is not null
    drop table #dummy_MBR

if object_id ('tempdb..#dummy_MBR','u') is null
    create table #dummy_MBR
     (
         IDENT        bigint identity
        ,MBR_KEY      char(32)
        ,BRND_TYP     varchar(15)
        ,REGLTG_BDY   varchar(50)
        ,MBR_FRST_NM  varchar(50)
        ,MBR_LAST_NM  varchar(50)
        ,DOB          date
        ,ADRS         varchar(100)
        ,ADRS_2       varchar(100)
        ,MBR_CITY     varchar(50)
        ,MBR_ST       char(2)
        ,MBR_ZIP_CD   char(5)
        ,HCID         varchar(50)
        ,PERS_CD      as cast(right('00'+right(HCID,1),2) as varchar(3))
        ,MCID         bigint
        ,AGE_CATG     as cast(case when datediff(year,DOB,eomonth(getdate(),-1)) < 18 then 'Child'
                                   else 'Adult' end as char(5))
        ,ZP_DRUG_DLVR char(1)
        ,CONSTRAINT PX_dummy_MBR_IDENT PRIMARY KEY NONCLUSTERED (IDENT)
        ,CONSTRAINT UQ_dummy_MBR_MBR_KEY UNIQUE NONCLUSTERED(MBR_KEY)
     )
     WITH (DATA_COMPRESSION = PAGE)


insert into #people
values
 ('A.','Mused')
,('Abby','Normal')
,('Addie','Minstra')
,('Aida','Bugg')
,('Al','Annon')
,('Al','Coholic')
,('Al E.','Gater')
,('Al','Zeimers')
,('Allie','Grater')
,('Amanda','Hug')
,('Amanda','Lynn')
,('Anita','Bath')
,('Anita','Letterback')
,('Anita','Room')
,('Ann','Chovey')
,('Anna','Domino')
,('Anna','Littlical')
,('Anna','Logwatch')
,('Anne','Gloindian')
,('Anne','Ortha')
,('Anne T.','Dote')
,('Anne T.','Kwayted')
,('Anne','Teak')
,('Anne','Thurium')
,('Annie','Versaree')
,('Art','Decco')
,('Arthur','Rightus')
,('Arty','Fischel')
,('Audie','Yose')
,('Augusta','Wind')
,('B.','Homesoon')
,('Barb','Akew')
,('Barry','Cuda')
,('Barry D.','Hatchett')
,('Barry','Kade')
,('Barry','Mundy')
,('Bea','Mine')
,('Ben','Dover')
,('Bennie','Factor')
,('Bess','Twishes')
,('Bridget','Theriveaquai')
,('C.','Yasoon')
,('Carmen','Goh')
,('Carmen','Sayid')
,('Carole','Singer')
,('Cesar','Salad')
,('Cherry','Blossom')
,('Chester','Minit')
,('Chris','Anthemum')
,('Chris P.','Bacon')
,('Chris P.','Creem')
,('Claude','Strophobia')
,('Clyde','Stale')
,('Col','Fays')
,('Colin','Sik')
,('Con','Junktivitas')
,('Con','Staninterupshuns')
,('Con','Trariweis')
,('Constance','Noring')
,('Coral','Trout')
,('Crystal','Ball')
,('Crystal','Shanda-Leer')
,('Dave','Allippa')
,('Dee','End')
,('Dee','Mandingboss')
,('Dee','Zynah')
,('Del','Phineum')
,('Des E.','Kaytedcoconut')
,('Des','Ignayshun')
,('Di','Ahreya')
,('Di','Allysis')
,('Dick','Tate')
,('Dinah','Mite')
,('Don','Keigh')
,('Don','Messwidme')
,('Doris','Shutt')
,('Drew A.','Head')
,('Dulcie','Veeta')
,('E.L.','Moray')
,('Earl E.','Bird')
,('Ed U.','Cayshun')
,('Eileen','Dover')
,('Eileen','Sideways')
,('Emma','Grate')
,('Emma','Nate')
,('Ester','La Vista')
,('Ev R.','Lasting')
,('Fay','Daway')
,('Faye','Clether')
,('Felix','Cited')
,('Fran G.','Pani')
,('Fran','Tick')
,('Frank','Furter')
,('Frank N.','Stein')
,('Gene','Eva Convenshun')
,('Gene','Therapee')
,('Gerry','Atrick')
,('Gilda','Lily')
,('Ginger','Plant')
,('Glad I.','Oli')
,('Gladys','Canby')
,('Greg','Arias')
,('Gus','Stroentereyetus')
,('Hank R.','Cheef')
,('Harriet','Upp')
,('Hazel','Nutt')
,('Hedda','Hare')
,('Helen','Hywater')
,('Herbie','Hind')
,('Holly','Wood')
,('Hope','Furaletter')
,('Horace','Cope')
,('Hugh','Jass')
,('Hugh','Mannerizorsa')
,('Hugh N.','Cry')
,('Hugh','Raye')
,('Hugo','First')
,('I. Missy','Ewe')
,('I.M.','Tired')
,('Ima','Hogg')
,('Iona','Mink')
,('Isabelle','Ringing')
,('Ivan','Itchinos')
,('Ivan','Notheridiya')
,('Ivana B.','Withew')
,('Jack','Aranda')
,('Jack','Pott')
,('Jay','Walker')
,('Jen','Tile')
,('Jim','Nasium')
,('Joe','King')
,('Joe V.','Awl')
,('John','Dory')
,('John','Quil')
,('Justin','Thyme')
,('Karen','Onnabit')
,('Kay','Oss')
,('Kirsten','Swore')
,('Lana Lynne','Creem')
,('Laura','Biding')
,('Laura','Norda')
,('Lee A.','Sun')
,('Lee','Nonmi')
,('Lee','Vitoff')
,('Levy','Tate')
,('Libby','Doe')
,('Lipin','Jection')
,('Liz','Erd')
,('Loco','Lyzayta')
,('Lois','Di Nominator')
,('Lois','Price')
,('Lori','Driver')
,('Lorne','Mowers')
,('Lynn C.','Doyle')
,('Lynn','O''Leeum')
,('Lynne','Gwafranca')
,('Lynne','Gwistic')
,('Mal','Ajusted')
,('Mal','Nurrisht')
,('Mand','Lynne')
,('Manny','Jah')
,('Manuel','Labor')
,('Marge','Areen')
,('Marius','Quick')
,('Mark','Ateer')
,('Marsha','Mellow')
,('Mary','Krismass')
,('Maureen','Biologist')
,('Max E.','Mumm')
,('May B.','Dunn')
,('Mel N.','Colley')
,('Mike','Rowe-Soft')
,('Miles A.','Head')
,('Minnie Van','Ryder')
,('Mona','Lott')
,('Murray','Cod')
,('Mustafa','Leek')
,('Neil','Down')
,('Norma Leigh','Absent')
,('Norma','Stitts')
,('Olive','Tree')
,('Olive','Yew')
,('Oscar','Nommanee')
,('P. Ann','O''Recital')
,('Paddy','O''Furniture')
,('Paige','Turner')
,('Pat N.','Toffis')
,('Pat','Thettick')
,('Patty','O''Furniture')
,('Peg','Legge')
,('Pedasso','Stu')
,('Penny','Black')
,('Percy','Kewshun')
,('Percy','Vere')
,('Perry','Scope')
,('Perry','Tonitus')
,('Pete','Tsar')
,('Peter','Owt')
,('Petra','Fried')
,('Phil','Landers')
,('Polly C.','Holder')
,('Polly Ester','Undawair')
,('Polly N.','Satcherayted')
,('Polly','Pipe')
,('Polly','Wannakrakouer')
,('Poppy','Cox')
,('Ray','Manta')
,('Ray','O''Sun')
,('Ray','Sin')
,('Red','Salmon')
,('Reeve','Ewer')
,('Reg','Oyce')
,('Rex','Cars')
,('Rhoda','Camel')
,('Rhoda','Report')
,('Rick','O''Shea')
,('Rita','Book')
,('Robyn','Banks')
,('Rock','Cod')
,('Rock','Lobster')
,('Rod','Knee')
,('Rose','Bush')
,('Rosemary','Lamb')
,('Roy L.','Commishun')
,('Russ','Tinayle')
,('Sal','Ami')
,('Sally','Forth')
,('Sam','Sung')
,('Sandy','Beech')
,('Santi','Argo')
,('Sarah','Moanees')
,('Sarah','Nader')
,('Saul','Goodmate')
,('Serge A.','Head')
,('Shirley U.','Care')
,('Simon','Sais')
,('Skye','Blue')
,('Sly','Meebuggah')
,('Sly','Meedentalfloss')
,('Stan','Dupp')
,('Stanley','Knife')
,('Staum','Clowd')
,('Teri','Dactyl')
,('Tex','Ryta')
,('Theresa','Green')
,('Tiger','Prawn')
,('Tim ''Buck''','Too')
,('Tim','Midsaylesman')
,('Titus','Zell')
,('Toi','Story')
,('Ty','Ayelloribbin')
,('Ty R.','Leeva')
,('U.R.','Nice')
,('Upton O.','Goode')
,('Uri','Nalisis')
,('Uri','Nerybladda')
,('Violet','Crumb-Ball')
,('Wade','Moore')
,('Warren','Peace')
,('Wayde N.','Thabalanz')
,('Wes','Yabinlatelee')
,('Wiley','Waites')
,('Willie','Findit')
,('Willie','Makit')
,('Wynn','Dozeaplikayshun')
,('Yul B.','Allwright')

insert into #place
values
 ('A Colorado Treasure','CO')
,('A Good Place to Live','IL')
,('A Moral Seaside Resort','NJ')
,('A Town with a Past','AR')
,('A Unique Little Town','CO')
,('Aerospace Capital of America','CA')
,('Air Capital','KS')
,('Air Crossroads','AK')
,('Alfafa Capital','NE')
,('Alien Capital','NM')
,('All American City','NC')
,('Almond Capital','CA')
,('Alpind Village','MI')
,('Always In Season','FL')
,('Always Turned On','NJ')
,('Amityville','MI')
,('Anchortown','AK')
,('Anemone Capital','NY')
,('Angel Grove','CA')
,('Angel Pine','CA')
,('Antique Capital of the Midwest','OH')
,('Appalachian Square Dance Capital','TN')
,('Apple Capital','MI')
,('Apple Capital','MN')
,('Arch City','OH')
,('Arkansas'' Original Boomtown','AR')
,('Armpit of California','CA')
,('Art City','UT')
,('Artichoke Center','CA')
,('Asparagus Capital','CA')
,('Athens of America','MA')
,('Athens of Florida','FL')
,('Athens of the Prairie','IN')
,('Athens of the South','TN')
,('Athens of the West','CA')
,('Atomic City','TN')
,('Avocado Capital','CA')
,('Azalea City','AL')
,('Azalea City','MD')
,('Azure City','WA')
,('B-More','MD')
,('Babecued Mutton Capital','KY')
,('Bagel Capital','IL')
,('Baghdad By the Bay','CA')
,('Bakers','CA')
,('Bako','CA')
,('Ballooning Capital of Alabama','AL')
,('Band City','PA')
,('Barbecued Pork Capital','TN')
,('Barbed Wire Capital','IL')
,('Bas Capital','AL')
,('Baseballtown','PA')
,('Basin City','NV')
,('Bass Capital of Texas','TX')
,('Bayou City','TX')
,('BBQ Capital','MO')
,('Beautiful View','CA')
,('Bedding Plant Capital','MI')
,('Bedding Plant Capital of Connecticut','CT')
,('Bedrock','ND')
,('Beehive of Industry','RI')
,('Beer Tent Capital','MI')
,('Berezerkeley','CA')
,('Berg','VA')
,('Best Little City By A Dam Site','IL')
,('Best Location In the Nation','OH')
,('Bicycle Capital of the Northwest','WA')
,('Big A','GA')
,('Big Apple','NY')
,('Big Brass Capital of Texas','TX')
,('Big D','TX')
,('Big Easy','LA')
,('Big Guava','FL')
,('Big Gun','GA')
,('Big O','NE')
,('Big Orange','CA')
,('Big Peach','GA')
,('Big Pineapple','HI')
,('Big Scrapple','PA')
,('Big Strawberry','CA')
,('Big Sweet Grass Break','SC')
,('Big Tamato','CA')
,('Bigfoot Capital','CA')
,('Biggest Little City In the World','NV')
,('Biggest Little Town in Arkansas','AR')
,('Biggest Little Town In Tennessee','TN')
,('Bikini Bottom','HI')
,('Billfish Capital','FL')
,('Bird Dog Capital','GA')
,('Birmingham of America','PA')
,('Birthplace of Acadiana','LA')
,('Birthplace of American Liberty','MA')
,('Birthplace of Aviation','OH')
,('Birthplace of Baseball','NY')
,('Birthplace of Country Music','VA')
,('Birthplace of General Motors','MI')
,('Birthplace of Jazz','LA')
,('Birthplace of Kool-Aid','NE')
,('Birthplace of Rock''n Roll','TN')
,('Birthplace of Route 66','MO')
,('Birthplace of Speed','FL')
,('Birthplace of the Motion Picture Industry','NJ')
,('Birthplace of the Republican Party','MI')
,('Birthplace to Basketball','MA')
,('Black Squirrel Capital','KS')
,('Blackberry Capital','CA')
,('Bludhaven','NJ')
,('Blue Chip City','OH')
,('Bluebird Capital of Texas','TX')
,('Bluff City','MO')
,('Bluff City','TN')
,('Boat','CO')
,('Bodymore','MD')
,('Bold New City of the South','FL')
,('Borough of Parks','NY')
,('Borough of Trees','NY')
,('Bourbon Capital','KY')
,('Bozone','MT')
,('Brass City','CT')
,('Brew City','WI')
,('Brick Capital','AR')
,('Brick City','NJ')
,('Bricktown','NY')
,('Bridgetown','OR')
,('Bright Side of the Bay','CA')
,('Broccoli Capital','CA')
,('Bucket','RI')
,('Buckle of the Bible Belt','TX')
,('Buffalo City','ND')
,('Burg','MO')
,('Burgh','PA')
,('Butterfly Capital','FL')
,('By Land Or By Sea','WA')
,('California''s Country Music Capital','CA')
,('Camellia','CA')
,('Camellia City','AL')
,('Canary City','CO')
,('Capital','NY')
,('Capital City','NH')
,('Capital of Alaska','AK')
,('Capital of Silicon Valley','CA')
,('Capital of Southern Hospitality','SC')
,('Capital of the South','AL')
,('Capital of the South Land','CA')
,('Carpet Capital','GA')
,('Carrot Capital','CA')
,('Castle Rock','ME')
,('Cataract City','NY')
,('Catfish Capitals','LA')
,('Cattle Capital of North Dakota','ND')
,('Celery Capital','CO')
,('Celery City','MI')
,('Celestial City','IL')
,('Cement And Steel Capital of Texas','TX')
,('Center of Good Living','FL')
,('Chair City','NC')
,('Charcoal Capital','MO')
,('Charm City','MD')
,('Chemical Capital','DE')
,('Cherry City','OR')
,('Cherry Pit Spitting Capital','MI')
,('Chi-Town','IL')
,('Chicago of the South','AL')
,('Chili Capital','TX')
,('Chili Pepper','NM')
,('Chimneyville','MS')
,('Chocolate Capital','PA')
,('Chocolate Town','PA')
,('Choice City','CO')
,('Christmas City','MA')
,('Christmas City','PA')
,('Christmas Pickle Capital','MI')
,('Christmas Town','CT')
,('Christmas Tree Capital','PA')
,('Christmas Tree City','CA')
,('Cigar Capital','FL')
,('Cigar City','FL')
,('Cincy','OH')
,('Circle City','CA')
,('Circle City','IN')
,('Circus Capital','IN')
,('Citrus Capital','CA')
,('City Beautiful','FL')
,('City Between the Canyons','UT')
,('City By the Bay','CA')
,('City By the Lake','TX')
,('City For Families','AL')
,('City In A Coma','NH')
,('City in a Garden','IL')
,('City In A Park','WA')
,('City In Motion','CA')
,('City In the Country','FL')
,('City In the Pines','AZ')
,('City of Angels','CA')
,('City of Best','AK')
,('City of Bolssoms','OH')
,('City of Bright Tomorrows','FL')
,('City of Brotherly Love','PA')
,('City of Champions','IL')
,('City of Choice','CO')
,('City of Churches','AR')
,('City of Destiny','WA')
,('City of Eagles','AL')
,('City of Eternal Sunshine','CA')
,('City of Festivals','LA')
,('City of Firsts','MD')
,('City of Five Flags','FL')
,('City of Five Seasons','IA')
,('City of Flags','MI')
,('City of Flour And Sawdust','MN')
,('City of Flowers','WA')
,('City of Flowers And Sunshine','CA')
,('City of Fountains','MO')
,('City of fountains and parks and bridges','AR')
,('City of Four Flags','MI')
,('City of Friendly People','WA')
,('City of Gold','CA')
,('City of Granite','GA')
,('City of Homes','GA')
,('City of Homes','PA')
,('City of Huguenots','NY')
,('City of Lakes','MN')
,('City of Lights and Flowers','AK')
,('City of Looms','NC')
,('City of Mills','CO')
,('City of Mystery','LA')
,('City of Natural Advantages','OH')
,('City of Notions','MA')
,('City of Oaks','NC')
,('City of Palms','FL')
,('City of Parks','NY')
,('City of Paved Streets','NV')
,('City of Power','TN')
,('City of Progress','FL')
,('City of Reads','MD')
,('City of Rocks','TN')
,('City of Roses','CA')
,('City of Seven Hills','MA')
,('City of Ships','ME')
,('City of Six Flags','AL')
,('City of Southern Hospitality','AL')
,('City of Spindles','MA')
,('City of Steel','IL')
,('City of Stone','IL')
,('City of the Century','IN')
,('City of the Chefs','LA')
,('City of the Great Blue Heron','WA')
,('City of the People','AL')
,('City of the Saints','UT')
,('City of the Seven Hills','VA')
,('City of the Seven Wonders','AZ')
,('City of the Straits','MI')
,('City of Witches','MA')
,('City of Youth And Ambition','CA')
,('City On the Move','AL')
,('City On the Move','TX')
,('City So Nice They Named It Twice','NY')
,('City that Care Forgot','LA')
,('City that Knows How','CA')
,('City that Lights And Hauls the World','NY')
,('City that Means Well','DE')
,('City that Moves Mountains','KY')
,('City that Never Sleeps','NY')
,('City that Saved Itself','IN')
,('City that Trees Built','NH')
,('City Too Busy to Hate','GA')
,('City Was So Nice They Named It Twice','WA')
,('City With A Legend','TX')
,('City With Soul','MS')
,('Clam Town','AK')
,('Classic City','GA')
,('Clay City','OH')
,('Climate Best By Government Test','CA')
,('Climate Capital of Colorado','CO')
,('Clipper City','MA')
,('Clock City','CT')
,('Clogging Capital','NC')
,('Cloud City','CA')
,('Cloudy','MN')
,('Coldest Spot In the Nation','MT')
,('Collar City','NY')
,('Colonial Capital','VA')
,('Colorado''s Last Great Ski Town','CO')
,('Colorado''s Wine Country','CO')
,('Comback City','MD')
,('Connecticuts Friendliest City','CT')
,('Connecticuts Smallest City','CT')
,('Corn City','OH')
,('Corn Cob Pipe Capital','MO')
,('Cotton Capital','MS')
,('Covered Dish Capital','KS')
,('Cow Chip Capital','OK')
,('Cow Chip Capital of Kansas','KS')
,('Cowboy Capital','TX')
,('Cowboy of Boot Capital','KS')
,('Cows','MN')
,('Cowtown','TX')
,('Crab Cake Capital','MD')
,('Crabtown','MD')
,('Cradle of Aviation','NY')
,('Cradle of History','CA')
,('Cradle of Louisiana Oil','LA')
,('Cradle of the Confederacy','AL')
,('Cradle of the Tennessee Walking Horse','TN')
,('Cradle of the Union','NY')
,('Crappie Capital','AL')
,('Crayfish Capital','LA')
,('Cream City','WI')
,('Crepe Myrtle City','AR')
,('Crescent City','LA')
,('Crossroads of America','IN')
,('Crossroads of Rhode Island','RI')
,('Crossroads of Silicon Valley','CA')
,('Crossroads of South Texas','TX')
,('Crossroads of the Nation','OH')
,('Crossroads of the West','UT')
,('Crown City','NY')
,('Crutch Capital','NH')
,('Crystal City','NY')
,('Cutting Horse Capital','KS')
,('Cutting Horse Capital','TX')
,('Czech Capital of Kansas','KS')
,('Czech Us Out','KS')
,('Dandelion Capital','NJ')
,('Danish Capital of America','CA')
,('Danish Capital of Nebraska','NE')
,('Date Capital','CA')
,('Deadwood City','CA')
,('Deer Capital of Nebraska','NE')
,('Denim Capital','NC')
,('Derry','ME')
,('Detroit of the West','CA')
,('Different City','NM')
,('Dillimore','CA')
,('Distict X','DC')
,('Do AC','NJ')
,('Dog-Mushing Center','AK')
,('Dogtown','CA')
,('Dogtrot Capital','LA')
,('Dogwood City','GA')
,('Dove Capital of Texas','TX')
,('Druid City','AL')
,('Drunk Driving Capital of America','NM')
,('Dubtown','OH')
,('Duck Capital','LA')
,('Dude Ranch Capital','AZ')
,('Durango Rocks','CO')
,('Dynamic City On the Bay','CA')
,('Dynamo of Dixie','TN')
,('Eagle Capital of America','AK')
,('Earmuff Capital','ME')
,('Earthport','NM')
,('Eerie','IN')
,('El Quebrados','CA')
,('Electric City','NY')
,('Elk Capital of Arkansas','AR')
,('Elm City','NH')
,('Emerald City','WA')
,('Emerald Coast','FL')
,('Empire City','NY')
,('End of the Rainbow','TX')
,('Endurance Capital','CA')
,('Entertainment Capital','CA')
,('European Masterpiece','LA')
,('Evergreen City','IL')
,('Everybody''s Favorite City','CA')
,('Execution Capital','TX')
,('Experience Our Sense of Yuma','AZ')
,('Fall City','KY')
,('Family City','UT')
,('Farm Toy Capital','IA')
,('Fat City','AL')
,('Favorite City','LA')
,('Fayettenam','NC')
,('Finest City','CA')
,('Fire Hydrant Capital','AL')
,('Firefly Capital','NC')
,('Fireworks Capital','PA')
,('First City of Alaska','AK')
,('First City of the West','MN')
,('First City On the Mississippi','MN')
,('First Cowtown In Kansas','KS')
,('First Resort','RI')
,('First Seaside Resort','NJ')
,('First Solar Village','WI')
,('First Town In the First State','DE')
,('Five Star City','MS')
,('Flag Town','AZ')
,('Flagship City','PA')
,('Flagstone Capital of the United States','AZ')
,('Flood City','PA')
,('Flour City','NY')
,('Flower Box City','MO')
,('Flower City','IL')
,('Flower City','NY')
,('Flower Seed Capital','CA')
,('Fog Capital','CA')
,('Fog City','CA')
,('Folk Arts and Crafts Capital of Kentucky','KY')
,('Folk Music Capital','AR')
,('Football Town','OK')
,('For A Day Or A Lifetime','WA')
,('Forged By Steel','WV')
,('Forgotten Borough','NY')
,('Fort Fun','CO')
,('Fort Law','NJ')
,('Fountain City','AL')
,('Fried Chicken Capital','KS')
,('Friendliest City','OH')
,('Friendly Village With Country Charm','IL')
,('Frisco','CA')
,('Frog Capital','LA')
,('Frog Jump Capital of Ohio','OH')
,('Fruit Cake Capital','TX')
,('Fruitcake Capital','GA')
,('Furniture Capital','NC')
,('Furniture Capital of New England','MA')
,('Furniture City','MI')
,('Gambling Capital','NV')
,('Garden City','MI')
,('Garden City','MT')
,('Garden of Eaton','CO')
,('Garden Spot of Colorado','CO')
,('Garlic Capital','CA')
,('Gate City','IA')
,('Gate City','NH')
,('Gateway to Mount Rainer','WA')
,('Gateway to New Hampshire','NH')
,('Gateway to Seattle','WA')
,('Gateway to the Americas','LA')
,('Gateway to the Black Hills','SD')
,('Gateway to the Delta','CA')
,('Gateway to the Gold Fields','CA')
,('Gateway to the New South','TN')
,('Gateway to the Peninsula','CA')
,('Gateway to the Plains','SD')
,('Gateway to the Redwoods','CA')
,('Gateway to the Rockies','CO')
,('Gateway to the Salton Sea','CA')
,('Gateway to the Sierra','CA')
,('Gateway to the West','MO')
,('Gateway to Yosemite','CA')
,('Gem City','IL')
,('Gem City','OH')
,('Gem City of the Plains','WY')
,('Gem City of the South West','TX')
,('Gem of Bayshore','NJ')
,('Gem of the Fox River','IL')
,('Gem of the Hill','AL')
,('Geographic Center of Connecticut','CT')
,('Georgia''s Apple Capital','GA')
,('Gibraltar of America','MS')
,('Glitter Gulch','NV')
,('Golden City','CA')
,('Golden City','IL')
,('Golden Gate City','CA')
,('Golden Heart City','AK')
,('Golf Capital','CA')
,('Good Land','CA')
,('Good People Surrounded By Badlands','MT')
,('Goose Capital','KS')
,('Goose Hunting Capital','TX')
,('Gotham City','NY')
,('Grain Palace City','ND')
,('Granite Capital','VT')
,('Granite City','GA')
,('Granite City','MN')
,('Grape Juice Capital','NY')
,('Grass Seed Capital','OR')
,('Graveyard of the Atlantic','NC')
,('Gravity Falls','OR')
,('Greatest City In America','MD')
,('Greatest Family Resort','NJ')
,('Green Tree City','MO')
,('Grits Capital of Georgia','GA')
,('Ground Hog Capital','WI')
,('Guernsey City','NJ')
,('Hackenslash','NJ')
,('Half Mile High City','KS')
,('Halibut Capital','AK')
,('Halloween Capital','MN')
,('Hamp','MA')
,('Hanging Basket Capital','AK')
,('Hangtown','CA')
,('Harbor City','FL')
,('Hard-hittin'' New Britain','CT')
,('Hardware City','CT')
,('Harm City','MD')
,('Hartford of the West','IA')
,('Hartford of the West','NE')
,('Hat City','CT')
,('Hay Capital','OK')
,('Health Care City','NJ')
,('Heart of Acadiana','LA')
,('Heart of America','KS')
,('Heart of Florida','FL')
,('Heart of Kansas','KS')
,('Heart of Mendocino City','CA')
,('Heart of Route 66','AZ')
,('Heart of Silicon Valley','CA')
,('Heights','CA')
,('High-Tech Oasis of the Silicon Desert','AZ')
,('Hill City','VA')
,('Hill Valley','CA')
,('Hog Capital','IL')
,('Hog Country','AR')
,('Hogsmeade','MA')
,('Hogtown','FL')
,('Home of 911','AL')
,('Home of America''s First Wave Pool','AL')
,('Home of Colleges','AR')
,('Home of Fort Rucker','AL')
,('Home of Heroes','CO')
,('Home of Mardi Gras','AL')
,('Home of Mike the Headless Chicken','CO')
,('Home of Popeye','IL')
,('Home of Superman','IL')
,('Home of the Alabama Gang','AL')
,('Home of the Blues','TN')
,('Home of the Candy Dance','NV')
,('Home of the Catfish Stomp','SC')
,('Home of the Ding Dong Daddy','AR')
,('Home of the Frozen Dead Guy','CO')
,('Home of the Homeless','CA')
,('Home of the Ivory-billed Wood Pecker','AR')
,('Home of the Oatmeal Festival','TX')
,('Home of the Superstition Mountains','AZ')
,('Home''s First Rodeo','CO')
,('Home''s Largest Ball of Twine','KS')
,('Home''s Largest Cheeto','IA')
,('Homemade Pie Capital','MN')
,('Homes Largest Pecan','MO')
,('Hometown','MA')
,('Honey Capital of the Nation','NE')
,('Horse Capital','KY')
,('Horse Town','CA')
,('Hotlanta','GA')
,('Hub','MA')
,('Hub City of the Plains','CO')
,('Hub of Morris Country','NJ')
,('Hub of the San Luis Valley','CA')
,('Hub of the Valley','MT')
,('Hubcap Capital','CA')
,('Hummingbird Capital of the United States','AZ')
,('Huntsvegas','AL')
,('Hyrule Castle','NH')
,('Ice cream Capital','IA')
,('Icebox of the United States','MN')
,('Industrial City','CA')
,('Indy','IN')
,('Insurance City','CT')
,('International City','CA')
,('International City','LA')
,('Iowa''s Irish Capital','IA')
,('Iris Capital','OR')
,('Iris City','GA')
,('Irish Riveria','NJ')
,('Iron City','PA')
,('Iron City','SC')
,('Jackalope Capital','WY')
,('Jambalaya Capital','LA')
,('James Michener''s Home In the West','CO')
,('Jax','FL')
,('Jazz Capital','MO')
,('Jet City','WA')
,('Jewel City','CA')
,('Jewel of the Prairie','IA')
,('Johnson Grass Capital','MS')
,('Kakariko Village','PR')
,('Kaolin Capital','GA')
,('Kentucky''s Country Music Capital','KY')
,('Killa City','MO')
,('King Crab Capital','AK')
,('King Salmon Capital','AK')
,('King''s Landing','NH')
,('Kingdom of Brekenridge','CO')
,('Kiwi Fruit Capital','CA')
,('Kolache Capital of Texas','TX')
,('Kolacky Capital','MN')
,('La-La Land','CA')
,('Lakeway to the Smokies','TN')
,('Land of Gracious Living','CA')
,('Land of Oz','KS')
,('Land of the Sleeping Giant','CT')
,('Las Brujas','CA')
,('Las Payasadas','CA')
,('Las Venturas','NV')
,('Latchkey to the White Mountains','NH')
,('Leap Year Capital','NM')
,('Leather City','MA')
,('Let Us Surprise You','WA')
,('Lettuce Capital','CA')
,('Liberty City','NY')
,('Lightning Capital','FL')
,('Like Nowhere Else','MA')
,('Lilac City','NH')
,('Lilac City','WA')
,('Lilac Village','IL')
,('Lily Growing Capital','CA')
,('Lima Bean Capital','CA')
,('Literary Center of the South','MS')
,('Little Apple','KS')
,('Little Chicago of the South','TN')
,('Little Easy','MS')
,('Little London','CO')
,('Little Manila','CA')
,('Little Mountain','MN')
,('Little Sweden','KS')
,('Little Switzerland of Ohio','OH')
,('Live Music Capital','TX')
,('Lobster Capital','ME')
,('Lock City','CT')
,('Lockport City','NY')
,('Logging Capital','WA')
,('Los Santos','CA')
,('Lost Wages','NV')
,('Lou','MO')
,('Loveliest Village on the Plains','AL')
,('Lumber City','NY')
,('Lumber Queen','MI')
,('Mad City','WI')
,('Magic City of the Plains','WY')
,('Mall City','MI')
,('ManchVega','NH')
,('Manhattan','NY')
,('Maple City','NY')
,('Maple Leaf City','MO')
,('Mardi Gras City','LA')
,('Marigold Capital','IL')
,('Marvel City','AL')
,('Maryland''s Gateway to the West','MD')
,('Mayhaw Capital','GA')
,('Melon Capital of Thw World','IL')
,('Metropolis','NY')
,('Mile High City','CO')
,('Mile-and-a-Quarter-High City','AZ')
,('Mill City','MN')
,('Milo Capital','KS')
,('Mineral City','IA')
,('Mini Apple','MN')
,('Mistake On the Lake','OH')
,('Mobtown','MD')
,('Monument City','MD')
,('Moose Capital of Michigan','MI')
,('Mordor','AZ')
,('More Then You Imagined','WA')
,('Mos Eisley','NM')
,('Most European City','LA')
,('Most Interesting City','LA')
,('Most Vertical City','AZ')
,('Motor City','MI')
,('Motorsports City','AL')
,('Motown','MI')
,('Muddy Frogwater Country','OR')
,('Mule Capital','TN')
,('Mule Packer Capital','CA')
,('Murderapolis','MN')
,('Mushroom Capital','MI')
,('Music City','TN')
,('Nail City','WV')
,('Naked City','IN')
,('Named for the Turn of a Card','AZ')
,('Napa Valley','CO')
,('Naptown','IN')
,('Nation''s Summer Capital','DE')
,('Natural Place to Visit','AK')
,('Nature''s Air Conditioned City','WV')
,('Nebraska''s 4th of July City','NE')
,('Nebraska''s Irish Capital','NE')
,('Neon Babylon','NV')
,('Neverland','CA')
,('New Donk City','NY')
,('New River City','VA')
,('New Vegas','NV')
,('New York of Alaska','AK')
,('Newport In the Rockies','CO')
,('Next America','MD')
,('Next Greatest City','FL')
,('Noho','MA')
,('North Coast','OH')
,('Norwegian Capital of Texas','TX')
,('Nursery Capital','TN')
,('Nylon Capital','DE')
,('Oaktown','CA')
,('Oasis of Nevada','NV')
,('Oil Capital','OK')
,('Old Pueblo','AZ')
,('Oleander','TX')
,('Olive City','CA')
,('Onion Capital','NY')
,('Onion City','VT')
,('Onion Fried Burger of America','OK')
,('Opal Capital','ID')
,('Orchard City','CA')
,('Orthopedic Capital','IN')
,('Our Name Speaks For Itself','OR')
,('Oyster Capital of Potomac','VA')
,('Paddlefish Capital','SD')
,('Palm Springs of Washington','WA')
,('Palmetto City','SC')
,('Panther City','TX')
,('Paper City','MA')
,('Paper City','MI')
,('Paradise','FL')
,('Paris of America','OH')
,('Paris of Americas','LA')
,('Paris of the Midwest','MI')
,('Paris of the Piedmont','NC')
,('Paris of the Plains','MO')
,('Paris of the South','LA')
,('Park City','CT')
,('Pawnee','IN')
,('Peach Capital','AR')
,('Peach Capital','TX')
,('Peach Capital of Colorado','CO')
,('Peach Capital of Georgia','GA')
,('Peach Capital of Kansas','KS')
,('Peak of Good Living','NC')
,('Peanut Capital','AL')
,('Peanut Capital','GA')
,('Peanut City','PA')
,('Pencil City','TN')
,('People''s Republic of Berkeley','CA')
,('People''s Republic of Boulder','CO')
,('People''s Republic of Davis','CA')
,('People''s Republic of Santa Monica','CA')
,('Peppermint Capital','IN')
,('Pheasant Capital of Kansas','KS')
,('Pie Capital of Louisiana','LA')
,('Pig''s Eye','MN')
,('Pilly','PA')
,('Pinto Bean Capital','CO')
,('Pinto Bean Capital','KS')
,('Pittsburgh of the South','AL')
,('Pittsburgh of the West','IN')
,('Play No Games','TX')
,('Playground','NJ')
,('Playground of the South','MS')
,('Plow Capital','IL')
,('Plymouth of the West','CA')
,('Poison Oak Capital','CA')
,('Poky','ID')
,('Polish Capital of Nebraska','NE')
,('Popcorn Capital','NE')
,('Porkopolis','OH')
,('Port City','MI')
,('Potato Capital','ID')
,('Potato Capital of the South Dakota','SD')
,('Poultry Capital','GA')
,('Prairie City','IN')
,('Preferred City','AL')
,('Pretzel Capital','PA')
,('Pretzel City','IL')
,('Pride City','CO')
,('Pride of the Swift-Growing South','AL')
,('Princess City','IN')
,('Printing Capital of the Nation','KS')
,('Prison City of Texas','TX')
,('Protestant Vatican','TN')
,('Prune Capital','CA')
,('Puritan City','MA')
,('Purple Martin Capital','KS')
,('Quahog','RI')
,('Quaker City','PA')
,('Quartz Crystal Capital','AR')
,('Queen City of Central West Texas','TX')
,('Queen City of the East','ME')
,('Queen City of the Ozarks','MO')
,('Queen City of the Plains','NE')
,('Queen City of the Prairie','MO')
,('Queen City of the Prarie','TX')
,('Queen City of the Rockies','MT')
,('Queen City of the Sound','NY')
,('Queen City of the South','LA')
,('Queen City of the Wabash','IN')
,('Queen of the Cowtowns','KS')
,('Queen of the Mississippi','LA')
,('Queen of the West','OH')
,('Questa Verde','CA')
,('Quiet Resorts','DE')
,('Quilt City','KY')
,('Ra-Cha-Cha','NY')
,('Racing Capital','IN')
,('Rail City','VT')
,('Railroad City','IN')
,('Raisin Capital','CA')
,('Raisinland','CA')
,('Rare Well Done','NE')
,('Razor Clam Capital','AK')
,('Real South Park','CO')
,('Real. America. Up Close','SD')
,('Red Carpet City of the South','MS')
,('Red Rock Country','AZ')
,('Red Tail Hawk Capital','TX')
,('Redbud Capital','VA')
,('Renaissance City','MI')
,('Renaissance City','RI')
,('Rhubarb Capital','SD')
,('Rhurbarb Pie Capital','WA')
,('Rice and Duck Capital','AR')
,('Richest Hill On Earth','MT')
,('Richest Square Mile On Earth','CO')
,('River City','AR')
,('Riverdale','KS')
,('Riviera of the Midwest','MI')
,('Rocket City','AL')
,('Rodeo Capital','WY')
,('Root Beer Capital','MS')
,('Rose Capital','TX')
,('Rose City','CT')
,('Rose City','NJ')
,('Rose Growing Capital','CA')
,('Round Town','OH')
,('Rubber City','CT')
,('Rumbling Waters','AL')
,('RV Capital','IN')
,('Sacraotomato','CA')
,('Sacto','CA')
,('Sactown','CA')
,('Sailing Capital','RI')
,('Saint City','LA')
,('Saintly City','MN')
,('Salt City','NY')
,('San Fierro','CA')
,('San Pornando','CA')
,('Sauerkraut','NY')
,('Sausage Capital of Texas','TX')
,('Sayyid Qutb''s Sodom and Gomorrah','CO')
,('Scenic City','TN')
,('Scholarship City','MA')
,('Scuba Capital of the Northwest','NM')
,('Seafood Capital','MD')
,('Seafood Capital of Alabama','AL')
,('Second City','IL')
,('Secret City','TN')
,('Seed Potato Capital','ID')
,('Sharks Tooth Capital','FL')
,('Shug','TX')
,('Silent Hill','ME')
,('Silicon Beach','CA')
,('Silicon Valley','IA')
,('Silk City','CT')
,('Silver Capital','ID')
,('Silver City','CT')
,('Silver City','MA')
,('Sin City','NV')
,('Sixth Borough','NJ')
,('Ski Town','CO')
,('Slate Capital','NY')
,('Slummerville','MA')
,('Smallville','KS')
,('Smoky City','PA')
,('Smoky Hill River City','KS')
,('Snack Capital','PA')
,('Snowshoe Capital','NY')
,('Sock Capital','AL')
,('Solar Energy Capital','CA')
,('Somaliwood','OH')
,('Soul of the Southwest','NM')
,('South Park','CO')
,('Southern Gateway to the Grand Mesa','CO')
,('Soviet Monica','CA')
,('Spa City','AR')
,('Spa City','NY')
,('Space City','TX')
,('Space Town','NH')
,('Spamtown','MN')
,('Spanish Peanut Capital','GA')
,('Speckled Perch Capital','FL')
,('Spinach Capital','AR')
,('Spoklahoma','WA')
,('Sponge Capital','FL')
,('Spotucky','WA')
,('Springs','CO')
,('Square Dance Capital','TX')
,('St. Jewish Park','MN')
,('St. Pete','FL')
,('Staff','AZ')
,('Star City','CA')
,('Star City','ME')
,('Star City of the North','VA')
,('Star of the West','SD')
,('Starlight Shores','PR')
,('Starvation Lake','MI')
,('Steel City','PA')
,('Steel City of the West','CO')
,('Strawberry Capital','OK')
,('Striped Bass Capital','OK')
,('Stumptown','OR')
,('Sturgeon Capital of Michigan','MI')
,('Submarine Capital','CT')
,('Summit City','IN')
,('Sunnydale','CA')
,('Sunshine City','AL')
,('Sunshine City','FL')
,('Sunshine Factory','AZ')
,('Super Bowl City','LA')
,('Surf City','CA')
,('Swedish Capital of Nebraska','NE')
,('Sweet Onion Capital','GA')
,('Sweetest Place On Earth','PA')
,('Switzerland of America','CO')
,('Taconite Capital','MN')
,('Take Me to the River','MS')
,('Tally','FL')
,('Tar Heel Town','NC')
,('Tennessee''s Oldest Town','TN')
,('Tennessee''s Top Spot','TN')
,('Test Market','OH')
,('Texas Tropics','TX')
,('Texas'' Biggest Small Town','TX')
,('Textile Capital','SC')
,('There Is No Night In Creede','CO')
,('Thread City','CT')
,('Thugz Mansion','CA')
,('Tierra Robada','CA')
,('Tinseltown','CA')
,('Title Town','GA')
,('To-hell-you-ride','CO')
,('Tokay Grape Capital','CA')
,('Tomato Capital','AL')
,('Tomato Capital','AR')
,('Tool Town','MA')
,('Toontown','CA')
,('Toothpick Capital','ME')
,('Torture Town','NC')
,('Town of Oil Repute','OK')
,('Town Too Beautiful to Burn','MS')
,('Town Too Tough to Die','AZ')
,('Township of Lakes','NJ')
,('Track Capital','AR')
,('Tracktown','OR')
,('Tree City','OH')
,('Tree Town','MI')
,('Trout Capital','ID')
,('Trout Capital','MN')
,('Trout Town','NY')
,('Truck Capital','PA')
,('Tuna Capital','RI')
,('Tunnel City','MA')
,('Turf Grass Capital','GA')
,('Turkey Capital','AR')
,('Turtle Town','IN')
,('Twice as Nice','AR')
,('Twin Peaks','WA')
,('Twin Ports','MN')
,('Twine City','OH')
,('Ultimate Rocky Mountain Hideout','CO')
,('University City of Maine','ME')
,('Vale of Paradise','IN')
,('Vehicle City','MI')
,('Venice of America','FL')
,('Venice of New Jersey','NJ')
,('Venusville','NM')
,('Vice City','FL')
,('Village With A Past the City With A Future','AK')
,('Ville','KY')
,('Walking Horse Capital','TN')
,('Wall Street West','NJ')
,('Walleye Capital','OH')
,('Washington''s Most Livable City','WA')
,('Watch City','MA')
,('Water Wealth Contentment Health','CA')
,('Watercress Capital','AL')
,('Waterpark','WI')
,('Weakfish Capital','NJ')
,('Weather Capital','PA')
,('West''s Most Western Town','AZ')
,('Whaling City','CT')
,('Wheat Capital','KS')
,('Where City and Country Flow Together','MN')
,('Where Everything Grows','CA')
,('Where Florida Begins','FL')
,('Where Progress Meets Preservation','AL')
,('Where the Geese Fly And the Bulls Cry','CO')
,('Where the Trails Start and the Buck Stops','MO')
,('Where the Trout Leap In the Main Street','WY')
,('Where the West Begins','TX')
,('Where Your Ship Comes In','MS')
,('Whip City','MA')
,('Whiskeytown','IL')
,('Wickedest Little City in America','KS')
,('Wild Goose Capital','MO')
,('Wild Hog Capital of Georgia','GA')
,('Wildflower Capital of Colorado','CO')
,('Wilmy','OH')
,('Windmill City','IL')
,('Windpower Capital','MN')
,('Windy City','IL')
,('Winter Strawberry Capital','FL')
,('Witch City','MA')
,('Wonderland','CA')
,('Wool Capital','TX')
,('World''s Fruit Basket','CA')
,('World''s Watermelon Capital','UT')
,('Worlds Most Beautiful Beaches','FL')
,('Wormtown','MA')
,('Young Lion of the West','NY')
,('Your Home For Family Fun','NJ')
,('Zenith City','MN')

insert into #zip_3 
values
 ('000',NULL)
,('001',NULL)
,('002',NULL)
,('003',NULL)
,('004',NULL)
,('005','NY')
,('006','PR')
,('007','PR')
,('008','VI')
,('009','PR')
,('010','MA')
,('011','MA')
,('012','MA')
,('013','MA')
,('014','MA')
,('015','MA')
,('016','MA')
,('017','MA')
,('018','MA')
,('019','MA')
,('020','MA')
,('021','MA')
,('022','MA')
,('023','MA')
,('024','MA')
,('025','MA')
,('026','MA')
,('027','MA')
,('028','RI')
,('029','RI')
,('030','NH')
,('031','NH')
,('032','NH')
,('033','NH')
,('034','NH')
,('035','NH')
,('036','NH')
,('037','NH')
,('038','NH')
,('039','ME')
,('040','ME')
,('041','ME')
,('042','ME')
,('043','ME')
,('044','ME')
,('045','ME')
,('046','ME')
,('047','ME')
,('048','ME')
,('049','ME')
,('050','VT')
,('051','VT')
,('052','VT')
,('053','VT')
,('054','VT')
,('055','MA')
,('056','VT')
,('057','VT')
,('058','VT')
,('059','VT')
,('060','CT')
,('061','CT')
,('062','CT')
,('063','CT')
,('064','CT')
,('065','CT')
,('066','CT')
,('067','CT')
,('068','CT')
,('069','CT')
,('070','NJ')
,('071','NJ')
,('072','NJ')
,('073','NJ')
,('074','NJ')
,('075','NJ')
,('076','NJ')
,('077','NJ')
,('078','NJ')
,('079','NJ')
,('080','NJ')
,('081','NJ')
,('082','NJ')
,('083','NJ')
,('084','NJ')
,('085','NJ')
,('086','NJ')
,('087','NJ')
,('088','NJ')
,('089','NJ')
,('090','AE')
,('091','AE')
,('092','AE')
,('093','AE')
,('094','AE')
,('095','AE')
,('096','AE')
,('097','AE')
,('098','AE')
,('099','AE')
,('100','NY')
,('101','NY')
,('102','NY')
,('103','NY')
,('104','NY')
,('105','NY')
,('106','NY')
,('107','NY')
,('108','NY')
,('109','NY')
,('110','NY')
,('111','NY')
,('112','NY')
,('113','NY')
,('114','NY')
,('115','NY')
,('116','NY')
,('117','NY')
,('118','NY')
,('119','NY')
,('120','NY')
,('121','NY')
,('122','NY')
,('123','NY')
,('124','NY')
,('125','NY')
,('126','NY')
,('127','NY')
,('128','NY')
,('129','NY')
,('130','NY')
,('131','NY')
,('132','NY')
,('133','NY')
,('134','NY')
,('135','NY')
,('136','NY')
,('137','NY')
,('138','NY')
,('139','NY')
,('140','NY')
,('141','NY')
,('142','NY')
,('143','NY')
,('144','NY')
,('145','NY')
,('146','NY')
,('147','NY')
,('148','NY')
,('149','NY')
,('150','PA')
,('151','PA')
,('152','PA')
,('153','PA')
,('154','PA')
,('155','PA')
,('156','PA')
,('157','PA')
,('158','PA')
,('159','PA')
,('160','PA')
,('161','PA')
,('162','PA')
,('163','PA')
,('164','PA')
,('165','PA')
,('166','PA')
,('167','PA')
,('168','PA')
,('169','PA')
,('170','PA')
,('171','PA')
,('172','PA')
,('173','PA')
,('174','PA')
,('175','PA')
,('176','PA')
,('177','PA')
,('178','PA')
,('179','PA')
,('180','PA')
,('181','PA')
,('182','PA')
,('183','PA')
,('184','PA')
,('185','PA')
,('186','PA')
,('187','PA')
,('188','PA')
,('189','PA')
,('190','PA')
,('191','PA')
,('192','PA')
,('193','PA')
,('194','PA')
,('195','PA')
,('196','PA')
,('197','DE')
,('198','DE')
,('199','DE')
,('200','DC')
,('201','VA')
,('202','DC')
,('203','DC')
,('204','DC')
,('205','DC')
,('206','MD')
,('207','MD')
,('208','MD')
,('209','MD')
,('210','MD')
,('211','MD')
,('212','MD')
,('213',NULL)
,('214','MD')
,('215','MD')
,('216','MD')
,('217','MD')
,('218','MD')
,('219','MD')
,('220','VA')
,('221','VA')
,('222','VA')
,('223','VA')
,('224','VA')
,('225','VA')
,('226','VA')
,('227','VA')
,('228','VA')
,('229','VA')
,('230','VA')
,('231','VA')
,('232','VA')
,('233','VA')
,('234','VA')
,('235','VA')
,('236','VA')
,('237','VA')
,('238','VA')
,('239','VA')
,('240','VA')
,('241','VA')
,('242','VA')
,('243','VA')
,('244','VA')
,('245','VA')
,('246','VA')
,('247','WV')
,('248','WV')
,('249','WV')
,('250','WV')
,('251','WV')
,('252','WV')
,('253','WV')
,('254','WV')
,('255','WV')
,('256','WV')
,('257','WV')
,('258','WV')
,('259','WV')
,('260','WV')
,('261','WV')
,('262','WV')
,('263','WV')
,('264','WV')
,('265','WV')
,('266','WV')
,('267','WV')
,('268','WV')
,('269',NULL)
,('270','NC')
,('271','NC')
,('272','NC')
,('273','NC')
,('274','NC')
,('275','NC')
,('276','NC')
,('277','NC')
,('278','NC')
,('279','NC')
,('280','NC')
,('281','NC')
,('282','NC')
,('283','NC')
,('284','NC')
,('285','NC')
,('286','NC')
,('287','NC')
,('288','NC')
,('289','NC')
,('290','SC')
,('291','SC')
,('292','SC')
,('293','SC')
,('294','SC')
,('295','SC')
,('296','SC')
,('297','SC')
,('298','SC')
,('299','SC')
,('300','GA')
,('301','GA')
,('302','GA')
,('303','GA')
,('304','GA')
,('305','GA')
,('306','GA')
,('307','GA')
,('308','GA')
,('309','GA')
,('310','GA')
,('311','GA')
,('312','GA')
,('313','GA')
,('314','GA')
,('315','GA')
,('316','GA')
,('317','GA')
,('318','GA')
,('319','GA')
,('320','FL')
,('321','FL')
,('322','FL')
,('323','FL')
,('324','FL')
,('325','FL')
,('326','FL')
,('327','FL')
,('328','FL')
,('329','FL')
,('330','FL')
,('331','FL')
,('332','FL')
,('333','FL')
,('334','FL')
,('335','FL')
,('336','FL')
,('337','FL')
,('338','FL')
,('339','FL')
,('340','AA')
,('341','FL')
,('342','FL')
,('343',NULL)
,('344','FL')
,('345',NULL)
,('346','FL')
,('347','FL')
,('348',NULL)
,('349','FL')
,('350','AL')
,('351','AL')
,('352','AL')
,('353',NULL)
,('354','AL')
,('355','AL')
,('356','AL')
,('357','AL')
,('358','AL')
,('359','AL')
,('360','AL')
,('361','AL')
,('362','AL')
,('363','AL')
,('364','AL')
,('365','AL')
,('366','AL')
,('367','AL')
,('368','AL')
,('369','AL')
,('370','TN')
,('371','TN')
,('372','TN')
,('373','TN')
,('374','TN')
,('375','TN')
,('376','TN')
,('377','TN')
,('378','TN')
,('379','TN')
,('380','TN')
,('381','TN')
,('382','TN')
,('383','TN')
,('384','TN')
,('385','TN')
,('386','MS')
,('387','MS')
,('388','MS')
,('389','MS')
,('390','MS')
,('391','MS')
,('392','MS')
,('393','MS')
,('394','MS')
,('395','MS')
,('396','MS')
,('397','MS')
,('398','GA')
,('399','GA')
,('400','KY')
,('401','KY')
,('402','KY')
,('403','KY')
,('404','KY')
,('405','KY')
,('406','KY')
,('407','KY')
,('408','KY')
,('409','KY')
,('410','KY')
,('411','KY')
,('412','KY')
,('413','KY')
,('414','KY')
,('415','KY')
,('416','KY')
,('417','KY')
,('418','KY')
,('419',NULL)
,('420','KY')
,('421','KY')
,('422','KY')
,('423','KY')
,('424','KY')
,('425','KY')
,('426','KY')
,('427','KY')
,('428',NULL)
,('429',NULL)
,('430','OH')
,('431','OH')
,('432','OH')
,('433','OH')
,('434','OH')
,('435','OH')
,('436','OH')
,('437','OH')
,('438','OH')
,('439','OH')
,('440','OH')
,('441','OH')
,('442','OH')
,('443','OH')
,('444','OH')
,('445','OH')
,('446','OH')
,('447','OH')
,('448','OH')
,('449','OH')
,('450','OH')
,('451','OH')
,('452','OH')
,('453','OH')
,('454','OH')
,('455','OH')
,('456','OH')
,('457','OH')
,('458','OH')
,('459','OH')
,('460','IN')
,('461','IN')
,('462','IN')
,('463','IN')
,('464','IN')
,('465','IN')
,('466','IN')
,('467','IN')
,('468','IN')
,('469','IN')
,('470','IN')
,('471','KY')
,('472','IN')
,('473','IN')
,('474','IN')
,('475','IN')
,('476','IN')
,('477','IN')
,('478','IN')
,('479','IN')
,('480','MI')
,('481','MI')
,('482','MI')
,('483','MI')
,('484','MI')
,('485','MI')
,('486','MI')
,('487','MI')
,('488','MI')
,('489','MI')
,('490','MI')
,('491','MI')
,('492','MI')
,('493','MI')
,('494','MI')
,('495','MI')
,('496','MI')
,('497','MI')
,('498','MI')
,('499','MI')
,('500','IA')
,('501','IA')
,('502','IA')
,('503','IA')
,('504','IA')
,('505','IA')
,('506','IA')
,('507','IA')
,('508','IA')
,('509','IA')
,('510','IA')
,('511','IA')
,('512','IA')
,('513','IA')
,('514','IA')
,('515','IA')
,('516','IA')
,('517',NULL)
,('518',NULL)
,('519',NULL)
,('520','IA')
,('521','IA')
,('522','IA')
,('523','IA')
,('524','IA')
,('525','IA')
,('526','IA')
,('527','IA')
,('528','IA')
,('529',NULL)
,('530','WI')
,('531','WI')
,('532','WI')
,('533',NULL)
,('534','WI')
,('535','WI')
,('536',NULL)
,('537','WI')
,('538','WI')
,('539','WI')
,('540','MN')
,('541','WI')
,('542','WI')
,('543','WI')
,('544','WI')
,('545','WI')
,('546','WI')
,('547','WI')
,('548','WI')
,('549','WI')
,('550','MN')
,('551','MN')
,('552',NULL)
,('553','MN')
,('554','MN')
,('555','MN')
,('556','MN')
,('557','MN')
,('558','MN')
,('559','MN')
,('560','MN')
,('561','MN')
,('562','MN')
,('563','MN')
,('564','MN')
,('565','MN')
,('566','MN')
,('567','ND')
,('568',NULL)
,('569',NULL)
,('570','SD')
,('571','SD')
,('572','SD')
,('573','SD')
,('574','SD')
,('575','SD')
,('576','SD')
,('577','SD')
,('578',NULL)
,('579',NULL)
,('580','ND')
,('581','ND')
,('582','ND')
,('583','ND')
,('584','ND')
,('585','ND')
,('586','ND')
,('587','ND')
,('588','ND')
,('589',NULL)
,('590','MT')
,('591','MT')
,('592','MT')
,('593','MT')
,('594','MT')
,('595','MT')
,('596','MT')
,('597','MT')
,('598','MT')
,('599','MT')
,('600','IL')
,('601','IL')
,('602','IL')
,('603','IL')
,('604','IL')
,('605','IL')
,('606','IL')
,('607','IL')
,('608','IL')
,('609','IL')
,('610','IL')
,('611','IL')
,('612','IL')
,('613','IL')
,('614','IL')
,('615','IL')
,('616','IL')
,('617','IL')
,('618','IL')
,('619','IL')
,('620','IL')
,('621',NULL)
,('622','IL')
,('623','IL')
,('624','IL')
,('625','IL')
,('626','IL')
,('627','IL')
,('628','IL')
,('629','IL')
,('630','MO')
,('631','MO')
,('632',NULL)
,('633','MO')
,('634','MO')
,('635','MO')
,('636','MO')
,('637','MO')
,('638','MO')
,('639','MO')
,('640','MO')
,('641','MO')
,('642',NULL)
,('643',NULL)
,('644','MO')
,('645','MO')
,('646','MO')
,('647','MO')
,('648','MO')
,('649','MO')
,('650','MO')
,('651','MO')
,('652','MO')
,('653','MO')
,('654','MO')
,('655','MO')
,('656','MO')
,('657','MO')
,('658','MO')
,('659',NULL)
,('660','KS')
,('661','KS')
,('662','KS')
,('663',NULL)
,('664','KS')
,('665','KS')
,('666','KS')
,('667','KS')
,('668','KS')
,('669','KS')
,('670','KS')
,('671','KS')
,('672','KS')
,('673','KS')
,('674','KS')
,('675','KS')
,('676','KS')
,('677','KS')
,('678','KS')
,('679','KS')
,('680','NE')
,('681','NE')
,('682',NULL)
,('683','NE')
,('684','NE')
,('685','NE')
,('686','NE')
,('687','NE')
,('688','NE')
,('689','NE')
,('690','NE')
,('691','NE')
,('692','NE')
,('693','NE')
,('694',NULL)
,('695',NULL)
,('696',NULL)
,('697',NULL)
,('698',NULL)
,('699',NULL)
,('700','LA')
,('701','LA')
,('702',NULL)
,('703','LA')
,('704','LA')
,('705','LA')
,('706','LA')
,('707','LA')
,('708','LA')
,('709',NULL)
,('710','LA')
,('711','LA')
,('712','LA')
,('713','LA')
,('714','LA')
,('715',NULL)
,('716','AR')
,('717','AR')
,('718','AR')
,('719','AR')
,('720','AR')
,('721','AR')
,('722','AR')
,('723','AR')
,('724','AR')
,('725','AR')
,('726','AR')
,('727','AR')
,('728','Ar')
,('729','AR')
,('730','OK')
,('731','OK')
,('732',NULL)
,('733','TX')
,('734','OK')
,('735','OK')
,('736','OK')
,('737','OK')
,('738','OK')
,('739','OK')
,('740','OK')
,('741','OK')
,('742',NULL)
,('743','OK')
,('744','OK')
,('745','OK')
,('746','OK')
,('747','OK')
,('748','OK')
,('749','OK')
,('750','TX')
,('751','TX')
,('752','TX')
,('753','TX')
,('754','TX')
,('755','TX')
,('756','TX')
,('757','TX')
,('758','TX')
,('759','TX')
,('760','TX')
,('761','TX')
,('762','TX')
,('763','TX')
,('764','TX')
,('765','TX')
,('766','TX')
,('767','TX')
,('768','TX')
,('769','TX')
,('770','TX')
,('771','TX')
,('772','TX')
,('773','TX')
,('774','TX')
,('775','TX')
,('776','TX')
,('777','TX')
,('778','TX')
,('779','TX')
,('780','TX')
,('781','TX')
,('782','TX')
,('783','TX')
,('784','TX')
,('785','TX')
,('786','TX')
,('787','TX')
,('788','TX')
,('789','TX')
,('790','TX')
,('791','TX')
,('792','TX')
,('793','TX')
,('794','TX')
,('795','TX')
,('796','TX')
,('797','TX')
,('798','TX')
,('799','TX')
,('800','CO')
,('801','CO')
,('802','CO')
,('803','CO')
,('804','CO')
,('805','CO')
,('806','CO')
,('807','CO')
,('808','CO')
,('809','CO')
,('810','CO')
,('811','CO')
,('812','CO')
,('813','CO')
,('814','CO')
,('815','CO')
,('816','CO')
,('817',NULL)
,('818',NULL)
,('819',NULL)
,('820','WY')
,('821','WY')
,('822','WY')
,('823','WY')
,('824','WY')
,('825','WY')
,('826','WY')
,('827','WY')
,('828','WY')
,('829','WY')
,('830','WY')
,('831','WY')
,('832','ID')
,('833','ID')
,('834','ID')
,('835','ID')
,('836','ID')
,('837','ID')
,('838','ID')
,('839',NULL)
,('840','UT')
,('841','UT')
,('842','UT')
,('843','UT')
,('844','UT')
,('845','UT')
,('846','UT')
,('847','UT')
,('848',NULL)
,('849',NULL)
,('850','AZ')
,('851',NULL)
,('852','AZ')
,('853','AZ')
,('854',NULL)
,('855','AZ')
,('856','AZ')
,('857','AZ')
,('858',NULL)
,('859','AZ')
,('860','AZ')
,('861',NULL)
,('862',NULL)
,('863','AZ')
,('864','AZ')
,('865','AZ')
,('866',NULL)
,('867',NULL)
,('868',NULL)
,('869',NULL)
,('870','NM')
,('871','NM')
,('872','NM')
,('873','NM')
,('874','NM')
,('875','NM')
,('876',NULL)
,('877','NM')
,('878','NM')
,('879','NM')
,('880','NM')
,('881','NM')
,('882','NM')
,('883','NM')
,('884','NM')
,('885','TX')
,('886',NULL)
,('887',NULL)
,('888',NULL)
,('889','NV')
,('890','NV')
,('891','NV')
,('892',NULL)
,('893','NV')
,('894','NV')
,('895','NV')
,('896',NULL)
,('897','NV')
,('898','NV')
,('899',NULL)
,('900','CA')
,('901','CA')
,('902','CA')
,('903','CA')
,('904','CA')
,('905','CA')
,('906','CA')
,('907','CA')
,('908','CA')
,('909',NULL)
,('910','CA')
,('911','CA')
,('912','CA')
,('913','CA')
,('914','CA')
,('915','CA')
,('916','CA')
,('917','CA')
,('918','CA')
,('919','CA')
,('920','CA')
,('921','CA')
,('922','CA')
,('923','CA')
,('924','CA')
,('925','CA')
,('926','CA')
,('927','CA')
,('928','CA')
,('929',NULL)
,('930','CA')
,('931','CA')
,('932','CA')
,('933','CA')
,('934','CA')
,('935','CA')
,('936','CA')
,('937','CA')
,('938','CA')
,('939','CA')
,('940','CA')
,('941','CA')
,('942','CA')
,('943','CA')
,('944','CA')
,('945','CA')
,('946','CA')
,('947','CA')
,('948','CA')
,('949','CA')
,('950','CA')
,('951','CA')
,('952','CA')
,('953','CA')
,('954','CA')
,('955','CA')
,('956','CA')
,('957','CA')
,('958','CA')
,('959','CA')
,('960','CA')
,('961','CA')
,('962','AP')
,('963','AP')
,('964','AP')
,('965','AP')
,('966','AP')
,('967','HI')
,('968','HI')
,('969','GU')
,('970','OR')
,('971','OR')
,('972','OR')
,('973','OR')
,('974','OR')
,('975','OR')
,('976','OR')
,('977','OR')
,('978','OR')
,('979','OR')
,('980','WA')
,('981','WA')
,('982','WA')
,('983','WA')
,('984','WA')
,('985','WA')
,('986','WA')
,('987',NULL)
,('988','WA')
,('989','WA')
,('990','WA')
,('991','WA')
,('992','WA')
,('993','WA')
,('994','WA')
,('995','AK')
,('996','AK')
,('997','AK')
,('998','AK')
,('999','AK')

insert into #adrs
select distinct AddressLine1, isnull([AddressLine2],'') AddressLine2
from AdventureWorksDW.dbo.DimCustomer c
inner join AdventureWorksDW.dbo.DimGeography g
on c.GeographyKey = g.GeographyKey
where CountryRegionCode = 'US'
and AddressLine1 like '[0-9]%'

--select * from #people
--select * from #place
--select * from #zip_3
--SELECT DATEADD(DAY, RAND(CHECKSUM(NEWID()))*(1+DATEDIFF(DAY, @StartDate, @EndDate)),@StartDate) AS 'SalesDate';
set nocount on
declare @max int = 1000
declare @i int = 0
while @i <= @max
begin
    insert into #dummy_MBR
    select
        @i AS MBR_KEY
       ,case when rand(checksum(newid())) <= 0.25 then 'B' else 'G' end AS BRND_TYP
       ,rg.reg AS REGLTG_BDY
       ,pp.F_NM AS MBR_FRST_NM
       ,pp.L_NM AS MBR_LAST_NM 
       ,dob.b_dt AS DOB
       ,aw.add1 AS ADRS
       ,aw.add2 AS ADRS_2
       ,pl.C_NM AS MBR_CITY
       ,pl.S_NM AS MBR_ST
       ,zp.zip AS MBR_ZIP_CD
       ,hid.hcid AS HCID
       ,try_cast(abs(checksum(newid())) as bigint) AS MCID
       ,case when rand(checksum(newid())) <= 0.005 then 'Y' else 'N' end AS ZP_DRUG_DLVR
    from (
          select top 1 F_NM, L_NM
          from #people
          order by newid()
         ) as pp
    cross apply     
         (
          SELECT top 1 DATEADD(DAY, RAND(CHECKSUM(NEWID()))*(1+DATEDIFF(DAY, @StartDate, @EndDate)),@StartDate)
         ) as dob (b_dt)
    cross apply
         (
          select top 1 C_NM, S_NM
          from #place
          order by newid()
         ) as pl  
    cross apply
         (
          select top 1 concat(zip3.ZIP3 , right('00'+cast(checksum(newid()) as varchar(20)),2)) as zip
          from #zip_3 zip3
          where zip3.S_NM = pl.S_NM
          order by newid()             
         ) zp (zip)
    cross apply
         (
          select top 1 add1, add2
          from #adrs
          order by newid() 
         ) aw
    cross apply
         (
          select case when rnd.num >= 0.0 and rnd.num <= 0.1 then 'Route of Administration'
                      when rnd.num >  0.1 and rnd.num <= 0.2 then 'Allowed Amount Agency'
                      when rnd.num >  0.2 and rnd.num <= 0.3 then 'Brands Bureau'
                      when rnd.num >  0.3 and rnd.num <= 0.4 then 'Coinsurance Cartel'
                      when rnd.num >  0.4 and rnd.num <= 0.5 then 'Department of Deductable'
                      when rnd.num >  0.5 and rnd.num <= 0.6 then 'Generics Gestapo'
                      when rnd.num >  0.6 and rnd.num <= 0.7 then 'Insurance Inquisition'
                      when rnd.num >  0.7 and rnd.num <= 0.8 then 'Manufacturers Ministry'
                      when rnd.num >  0.8 and rnd.num <= 0.9 then 'Copay Committee'
                      when rnd.num >  0.8 and rnd.num <= 0.9 then 'Prescriber Penmanship Program'
                      when rnd.num >  0.9 and rnd.num <= 1.0 then 'Section of Symptoms and Side Effects'
                      end as reg
          from (
                select rand(checksum(newid()))  
               ) rnd (num)          
         ) rg
    cross apply (
                 select CHAR(65+((51+0.5+CAST(rand(checksum(newid()))*52 AS INT)*0.5)%26))
                      + CHAR(65+((51+0.5+CAST(rand(checksum(newid()))*52 AS INT)*0.5)%26))
                      + CHAR(65+((51+0.5+CAST(rand(checksum(newid()))*52 AS INT)*0.5)%26))
                      + right('0000' + REPLACE(cast(rand(checksum(newid())) as varchar(20)),'.',''),4)
                      + right('0000' + REPLACE(cast(rand(checksum(newid())) as varchar(20)),'.',''),4) 
               + Case when rnd.num >= 0.0 and rnd.num <= 0.4 then '1'
                      when rnd.num >  0.4 and rnd.num <= 0.7 then '2'
                      when rnd.num >  0.7 and rnd.num <= 0.9 then '3'
                      when rnd.num >  0.9 and rnd.num <= 0.94 then '4'
                      when rnd.num >  0.94 and rnd.num <= 0.97 then '5'
                      when rnd.num >  0.97 and rnd.num <= 0.99 then '6'
                      when rnd.num >  0.99 and rnd.num <= 1.0 then '7'
                      end as hcid                      
                from (
                      select rand(checksum(newid()))  
                     ) rnd (num)  
                ) hid 
    set @i += 1
end
set nocount off
select * from #dummy_MBR


--select CHAR(65+((51+0.5+CAST(rand(checksum(newid()))*52 AS INT)*0.5)%26)) AS WeekLetter
