DROP PROCEDURE IF EXISTS #T1
GO

CREATE PROCEDURE #T1 AS
CREATE TABLE #Temp1 (Col1 int)
IF @@NESTLEVEL <= 10
    EXEC #T1
IF @@NESTLEVEL = 10
    SELECT * FROM tempdb.sys.tables AS t WHERE name LIKE '#Temp1%'
GO

CREATE TABLE #Temp1 (Col1 int)
EXEC #T1;
DROP TABLE #Temp1
GO
